/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutIndexRouteImport } from './routes/workout.index'
import { Route as WorkoutDayIdRouteImport } from './routes/workout.$dayId'
import { Route as WorkoutDayNewRouteImport } from './routes/workout.day.new'
import { Route as WorkoutDayDayIdEditRouteImport } from './routes/workout.day.$dayId.edit'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIndexRoute = WorkoutIndexRouteImport.update({
  id: '/workout/',
  path: '/workout/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutDayIdRoute = WorkoutDayIdRouteImport.update({
  id: '/workout/$dayId',
  path: '/workout/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutDayNewRoute = WorkoutDayNewRouteImport.update({
  id: '/workout/day/new',
  path: '/workout/day/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutDayDayIdEditRoute = WorkoutDayDayIdEditRouteImport.update({
  id: '/workout/day/$dayId/edit',
  path: '/workout/day/$dayId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/workout/$dayId': typeof WorkoutDayIdRoute
  '/workout/': typeof WorkoutIndexRoute
  '/workout/day/new': typeof WorkoutDayNewRoute
  '/workout/day/$dayId/edit': typeof WorkoutDayDayIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/workout/$dayId': typeof WorkoutDayIdRoute
  '/workout': typeof WorkoutIndexRoute
  '/workout/day/new': typeof WorkoutDayNewRoute
  '/workout/day/$dayId/edit': typeof WorkoutDayDayIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/workout/$dayId': typeof WorkoutDayIdRoute
  '/workout/': typeof WorkoutIndexRoute
  '/workout/day/new': typeof WorkoutDayNewRoute
  '/workout/day/$dayId/edit': typeof WorkoutDayDayIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/nutrition'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/workout/$dayId'
    | '/workout/'
    | '/workout/day/new'
    | '/workout/day/$dayId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/nutrition'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/workout/$dayId'
    | '/workout'
    | '/workout/day/new'
    | '/workout/day/$dayId/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/home'
    | '/nutrition'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/workout/$dayId'
    | '/workout/'
    | '/workout/day/new'
    | '/workout/day/$dayId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
  NutritionRoute: typeof NutritionRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  WorkoutDayIdRoute: typeof WorkoutDayIdRoute
  WorkoutIndexRoute: typeof WorkoutIndexRoute
  WorkoutDayNewRoute: typeof WorkoutDayNewRoute
  WorkoutDayDayIdEditRoute: typeof WorkoutDayDayIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/': {
      id: '/workout/'
      path: '/workout'
      fullPath: '/workout/'
      preLoaderRoute: typeof WorkoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$dayId': {
      id: '/workout/$dayId'
      path: '/workout/$dayId'
      fullPath: '/workout/$dayId'
      preLoaderRoute: typeof WorkoutDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/day/new': {
      id: '/workout/day/new'
      path: '/workout/day/new'
      fullPath: '/workout/day/new'
      preLoaderRoute: typeof WorkoutDayNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/day/$dayId/edit': {
      id: '/workout/day/$dayId/edit'
      path: '/workout/day/$dayId/edit'
      fullPath: '/workout/day/$dayId/edit'
      preLoaderRoute: typeof WorkoutDayDayIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
  NutritionRoute: NutritionRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  WorkoutDayIdRoute: WorkoutDayIdRoute,
  WorkoutIndexRoute: WorkoutIndexRoute,
  WorkoutDayNewRoute: WorkoutDayNewRoute,
  WorkoutDayDayIdEditRoute: WorkoutDayDayIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
