/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutDayIdRouteImport } from './routes/workout.$dayId'
import { Route as WorkoutDayNewRouteImport } from './routes/workout.day.new'

const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutDayIdRoute = WorkoutDayIdRouteImport.update({
  id: '/$dayId',
  path: '/$dayId',
  getParentRoute: () => WorkoutRoute,
} as any)
const WorkoutDayNewRoute = WorkoutDayNewRouteImport.update({
  id: '/day/new',
  path: '/day/new',
  getParentRoute: () => WorkoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRouteWithChildren
  '/workout/$dayId': typeof WorkoutDayIdRoute
  '/workout/day/new': typeof WorkoutDayNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRouteWithChildren
  '/workout/$dayId': typeof WorkoutDayIdRoute
  '/workout/day/new': typeof WorkoutDayNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRouteWithChildren
  '/workout/$dayId': typeof WorkoutDayIdRoute
  '/workout/day/new': typeof WorkoutDayNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/nutrition'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/workout'
    | '/workout/$dayId'
    | '/workout/day/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/nutrition'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/workout'
    | '/workout/$dayId'
    | '/workout/day/new'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/nutrition'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/workout'
    | '/workout/$dayId'
    | '/workout/day/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  NutritionRoute: typeof NutritionRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  WorkoutRoute: typeof WorkoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$dayId': {
      id: '/workout/$dayId'
      path: '/$dayId'
      fullPath: '/workout/$dayId'
      preLoaderRoute: typeof WorkoutDayIdRouteImport
      parentRoute: typeof WorkoutRoute
    }
    '/workout/day/new': {
      id: '/workout/day/new'
      path: '/day/new'
      fullPath: '/workout/day/new'
      preLoaderRoute: typeof WorkoutDayNewRouteImport
      parentRoute: typeof WorkoutRoute
    }
  }
}

interface WorkoutRouteChildren {
  WorkoutDayIdRoute: typeof WorkoutDayIdRoute
  WorkoutDayNewRoute: typeof WorkoutDayNewRoute
}

const WorkoutRouteChildren: WorkoutRouteChildren = {
  WorkoutDayIdRoute: WorkoutDayIdRoute,
  WorkoutDayNewRoute: WorkoutDayNewRoute,
}

const WorkoutRouteWithChildren =
  WorkoutRoute._addFileChildren(WorkoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  NutritionRoute: NutritionRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  WorkoutRoute: WorkoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
